### ISSUE TITLE
A Few Questions..

### ISSUE THREAD

**Issue by LouisPi** [zafartahirov/fingerpi#11]
1. Does this work with a Pi 2 Model B?
2. Where do I add my own code to happen after the scanner detects the right fingerprint on the GUI code (that is presuming you can save then recognise a fingerprint)?
Thanks in advance,
LouisPi

**Comment by zafartahirov** [comment]
1. I have no idea -- try it out, and let me know
2. Nowhere -- the gui code is for demo only, you will have to write your own codes
