### ISSUE TITLE
Where are the images stored?

### ISSUE THREAD

**Issue by danielsrouji** [zafartahirov/fingerpi#14]
so im getting the image to be captured and its time to transmit, however my gt511c3 fingerprint scanner does not light up, and i would like to ask where is my transmitted image stored and how may i view that?

**Comment by zafartahirov** [comment]
The images are stored in a pickle file `raw_img.pickle` (see https://github.com/zafartahirov/fingerpi/blob/93c91ec023d50668f817daefb369cf9e6e30b535/demo.py#L65)
