### ISSUE TITLE
Issue with Enrollment 

### ISSUE THREAD

**Issue by jsn5** [zafartahirov/fingerpi#17]
Hi, I got the sensor to run the demo.py. I'm trying to do the enrollment part. The fingerprint enrollment function enroll3() is not working for me.

This is my enrollment function
```

def Enroll():
    enroll_id = 1
    okid = True
    while okid == True:
        okid = f.CheckEnrolled(enroll_id)
        if okid == True:
            enroll_id+=1
    f.CmosLed(True)
    
    f.EnrollStart(enroll_id)
    print("Place finger..")
    while True:

        resp = f.IsPressFinger()
        if resp[0]['Parameter'] == 0:
            response = f.CaptureFinger(True)
            enr = f.Enroll1()
            print(enr)
            print("remove finger")
            time.sleep(5)
            break

    print("Place same finger again..")
    while True:

        resp = f.IsPressFinger()
        if resp[0]['Parameter'] == 0:
            response = f.CaptureFinger(True)
            enr = f.Enroll2()
            print(enr)
            print("remove finger")
            time.sleep(5)
            break

    print("place same finger again..")
    while True:

        resp = f.IsPressFinger()
        if resp[0]['Parameter'] == 0:
            response = f.CaptureFinger(True)
            enr = f.Enroll3()
            print(enr)
            print("remove finger")
            break



    f.CmosLed(False)
    
```

Here is my output.

```
Opening connection...
Changing baudrate...
Place finger..
[{'ACK': True, 'Header': '55aa', 'Parameter': 0, 'DeviceID': '1', 'Checksum': True}, None]
remove finger
Place same finger again..
[{'ACK': True, 'Header': '55aa', 'Parameter': 0, 'DeviceID': '1', 'Checksum': True}, None]
remove finger
place same finger again..
[{'ACK': False, 'Header': '55aa', 'Parameter': 0, 'DeviceID': '1', 'Checksum': True}, None]
remove finger
```

Enroll1() and Enroll2() seems to be working but Enroll3() is returning false. 

What could be the problem here?

**Comment by achraf-boussaada** [comment]
Hey .. when i executed your code and after Enroll3() it returns also false but in the Parameter gives me this error > 'Parameter': 'NACK_TURN_ERR' which means that there is problem by the order of the enrollement ...
Normaly it goes like that > (Obsolete) Invalid order of the enrollment #    (EnrollStart->Enroll1->Enroll2->Enroll3)

But in your order is right ... did you solve your problem ??

**Comment by achraf-boussaada** [comment]
in case you didnt find a solution  this might help.
i changed the first part of your code and made it look like this >
`		okid = False
		while okid == False:
			checkIdResponse = f.CheckEnrolled(enroll_id)
			if checkIdResponse[0]['Parameter'] != 'NACK_IS_NOT_USED' :
				enroll_id+=1
			else :
				okid = True`

and in the final enroll added the line okid = False >

`				if resp[0]['Parameter'] == 0:
					response = f.CaptureFinger(True)
					enr = f.Enroll3()
					print(enr)
					print("remove finger")
					okid = False
					break`

now everything works fine

**Comment by jsn5** [comment]
Yeah, I had got it running. Yes, the issue was with the check for enrollment id. Thanks anyways. This might be help others trying as I haven't found any examples for enrollment yet. Cheers!
