### ISSUE TITLE
Where am I making mistakes?

### ISSUE THREAD

**Issue by bahadiracar** [zafartahirov/fingerpi#21]
#########################################################################
root@cloudpi:/home/pi/Desktop/fingerpi-master# python2 interactive.py 
Traceback (most recent call last):
  File "interactive.py", line 12, in <module>
    curses.wrapper(processmenu,menu_data) # For the error handling
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/pi/Desktop/fingerpi-master/gui/interactive.py", line 166, in processmenu
    status_mid, status_bottom = processmenu(screen, menu['options'][getin], menu, status_bottom) # display the submenu, and make sure the status is persistent
  File "/home/pi/Desktop/fingerpi-master/gui/interactive.py", line 154, in processmenu
    getin = runmenu(screen, menu, parent, status_mid, status_bottom)
  File "/home/pi/Desktop/fingerpi-master/gui/interactive.py", line 65, in runmenu
    screen.addstr(5+index,4, "{0:d} - {1!s}".format(index+1, menu['options'][index]['title']), textstyle)
_curses.error: addstr() returned ERR
#########################################################################

I changed the connection port    =>   port = '/dev/ttyS0'
Please help me...

Raspberry Pi 3 Model B v.2
FPS GT-511C3

**Comment by zafartahirov** [comment]
This is an error related to the `curses` package. Can you post which version of `curses` you are using? Also, while at it, give the version of Python (I am assuming it's 2, but what is the exact version). Also, please, confirm that the device is actually working on the `dev/ttyS0`

**Comment by dapi115** [comment]
I have the same error with 2 different images on Raspberry Pi 2 Model B
FPS GT-521F32 (full compatible with GT-511C3) :-)

Raspbian Stretch Lite Kernel 4.14.52+ #1123
Python 2.7.13
Curses 2.2

Raspbian Jessie Lite Kernel 4.9.35+ #1014
Python 2.7.9
Curses 2.2

I have no idea to change version of curses. Its part of Python modules...

What versions are running on referenz-system?
Do you have any idea for solving this issue??

Best regards
Daniel

**Comment by zafartahirov** [comment]
After a quick search, it looks like it's a problem with vertical scrolling. This error will happen if your window is either too small (vertically) or there are too many options in the menu. I created a little fix -- it might or might not be enough. If you have a more permanent fix, please, feel free to submit it.

**Comment by zafartahirov** [comment]
Fixed in 7377343
