### ISSUE TITLE
Script stay stuck at beginning

### ISSUE THREAD

**Issue by chopesquad** [zafartahirov/fingerpi#4]
Hi, When I run the script, it run and  disp "Opening connection.." and nothing else. Please could you help me the script seems blocked. 

NP: Sorry for my English :)

**Comment by zafartahirov** [comment]
This is not very helpful -- can you post what is the RPi you are using, how is it connected, did you try running the functions separately, and not as part of the demo script?

**Comment by chopesquad** [comment]
Hi, I use a raspberry pi 3 that i connected like written in the readme file for the raspberry pi. I'll try to run the script separately thursday. Thank's for helping me.

**Comment by chopesquad** [comment]
i fixed my previous error now i get the following:
`Opening connection...
Changing baudrate...
Place the finger on the scanner and press <Enter>

Traceback (most recent call last):
  File "/home/pi/fingerpi/demo.py", line 29, in <module>
    response = f.CaptureFinger()
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 226, in CaptureFinger
    return [self.getResponse(), None]
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 50, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/fingerpi/fingerpi/base.py", line 95, in decode_command_packet
    checksum = sum(struct.unpack(checksum_struct(), packet[-2:])) # Last two bytes are checksum
struct.error: unpack requires a string argument of length 2
`

or 

`Opening connection...
Traceback (most recent call last):
  File "/home/pi/fingerpi/demo.py", line 18, in <module>
    f.Open(extra_info = True, check_baudrate = True)
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 77, in Open
    response = self.getResponse()
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 50, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/fingerpi/fingerpi/base.py", line 102, in decode_command_packet
    raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack requires a string argument of length 10 0
`

When I run it again.
Could you help ? ;)

**Comment by chopesquad** [comment]
Now i got the followinf error when i try to enroll a fingerprint with interactive script  error : 
`Traceback (most recent call last):
  File "/home/pi/fingerpi/interactive.py", line 12, in <module>
    curses.wrapper(processmenu,menu_data) # For the error handling
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/pi/fingerpi/fingerpi/interactive.py", line 173, in processmenu
    status_mid, status_bottom = processrequest(menu['options'][getin], screen) # Add additional space
  File "/home/pi/fingerpi/fingerpi/interactive.py", line 136, in processrequest
    status = eval('C.'+menu['command'])(screen, **menu['kwargs']) # Give it the subwindow, just in case!
  File "<string>", line 1
    C.
     ^
SyntaxError: unexpected EOF while parsing
`

**Comment by rirozizo** [comment]
how did you solve your previous problem where it got stuck on opening connection?

**Comment by chopesquad** [comment]
The problem was a misconfiguration of the raspberry pi : you need to enable the uart serial.
I follow these tutorial:
[http://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3](url)
[https://www.abelectronics.co.uk/kb/article/1035/raspberry-pi-3-serial-port-usage)](url)

**Comment by chopesquad** [comment]
Now, the demo script work the first time I run it, but don't the other.
I'll tell you if i find a way to solve this, but is someone have an idea how to ?

**Comment by zafartahirov** [comment]
The `demo.py` script is just for demo purposes. It is not supposed to be used in production! This is just a bridge API, and `demo` just shows an example on how to use it. It is not supposed to work second time, because it changes the baudrate, and does not remember that! You will have to write your own code using this template if you want to be able to make it production worthy.

**Comment by VenethKumar0808** [comment]
Hello zafartahirov,

While running demo after I enter fingerprint and hit Enter I got this error

raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack requires a string argument of length 10 16

How to fix it?

Please help me!

**Comment by peterwilli** [comment]
@VenethKumar0808 I had the same problem. I found a solution:

- Run `sudo raspi-config`
- Go to Interfacing Options
- Select Serial
- Disable Shell over Serial
- Enable hardware serial port
- Finish and reboot
- It should work now!
