### ISSUE TITLE
how can install the package

### ISSUE THREAD

**Issue by annayusoff** [zafartahirov/fingerpi#6]
hi. how can i install the package? i had done 

git clone https://github.com/zafartahirov/fingerpi.git
pip install fingerpi

but it cannot install the package. i also had done 

pip install git+https://github.com/zafartahirov/fingerpi.git

but also it does not work. it keep said that "Could not find a version that satisfies the requirement fingerpi (from versions: )
No matching distribution found for fingerpi " 
please help me

**Comment by zafartahirov** [comment]
This package does not include the `setup.py` file, and cannot be installed. `pip` version of this package _might_ be developed in the future. For now, you have to use it as is
