### ISSUE TITLE
Unknown Error occured None

### ISSUE THREAD

**Issue by skylite21** [zafartahirov/fingerpi#7]
I am trying to use the  GT-511C3 with my zero:

```
(fingerpi) skylite@zero $sudo python demo.py
Opening connection...
Changing baudrate...
Place the finger on the scanner and press <Enter>

Unknown Error occured None
Place the finger on the scanner and press <Enter>
^CTraceback (most recent call last):
  File "demo.py", line 26, in <module>
    _ = raw_input()
KeyboardInterrupt
(fingerpi) skylite@zero $
```
This is how I connected the  GT-511C3 to the zero:
![photo 2017 05 23 13 36 31](https://cloud.githubusercontent.com/assets/7330136/26353195/7c01d538-3fbf-11e7-8a65-54a162c9c72c.jpg)

Any Ideas how to debug this?

My /boot/cmdline.txt looks like this:

root=/dev/mmcblk0p2 rw rootwait console=tty1 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 elevator=noop

And I disabled  and stooped getty on serial with:

sudo systemctl stop serial-getty@ttyAMA0.service
sudo systemctl mask serial-getty@ttyAMA0.service

my virtualenv is running Python 2.7.13

**Comment by zafartahirov** [comment]
Several things:
* Avoid using `sudo` when running your own commands! You don't know what I put in those python codes, I might be opening back door to your machine
* Current repository was one of the earlier projects I had, and is not designed to be a diagnostic tool -- it assumes that you already have the scanner working and provides a bridge between Python and the device.
* To debug, don't run the codes from this repo -- try making the scanner work using a terminal

**Comment by ritvikiitkgp** [comment]
@zafartahirov how to try making the scanner work using a terminal?

**Comment by ritvikiitkgp** [comment]
I'm working on the same fingerprint sensor using raspberry pi 3 model B, and I am also facing many issues.

**Comment by skylite21** [comment]
@ritvikiitkgp I think he means try to connect the sensor via serial (ex. screen) and send-recevie raw packets to it with the help of the documentation ( https://cdn.sparkfun.com/datasheets/Sensors/Biometric/GT-511C3_datasheet_V2.1_20161025.pdf ) Or At least thats what I'll try once my CH340G Serial Converter arrives.  As for the sudo lessons, I added my user to the uucp group so I can connect to /dev/ttyAMA0 without permission issues.  😇

**Comment by ritvikiitkgp** [comment]
@skylite21 were you able to get your GT511C3 to work with raspberry pi 3?

**Comment by skylite21** [comment]
no @ritvikiitkgp I try it on a raspberry zero (running arch linux) but since it doesn't work via serial, I will try it with a  CH340G Serial Converter.

**Comment by ritvikiitkgp** [comment]
@skylite21 okay.
I've tried almost everything.
@zafartahirov 
I also tried going through Raspberry 3 compatibility issue thread(closed one), tried the code that you mentioned in the end. The output I received was:
Send status: 12
Resp len : 0
Response: []
I don't know how to make this device work. Little help please. I understand that this is just a demo, but I need to get this working to get started.

**Comment by zafartahirov** [comment]
If you receive no response, your baudrate is not right (most probably). This problem is outsid eof the scope of this project, which just provides an interface to already connected sensor. Try using `interactive.py` if you want to debug your setup.
