### ISSUE TITLE
Should i use a resistor for connecting GT 511c3 fingerprint scanner with raspberry pi 3?

### ISSUE THREAD

**Issue by Abhiramianbu** [zafartahirov/fingerpi#8]
I am new to electronics . 
Your second diagram in readme shows some resistance . But why should we use resistor?
Does it have anything to do with 5vttl?

**Comment by chaitanya4b3** [comment]
It is not needed if you are testing for time being.
But in the long run the current ratings may damage your sensor, so the resistance damages the sensor, because of excess current.

**Comment by zafartahirov** [comment]
You don't have to if:
* You have only one device connecting to the host
* The host is low-current, low-power device
* You don't need voltage division or voltage step-down

On the second diagram, we have a 5V source, 3.3V sensor. Most of the time nothing would happen, but sometimes it might damage the sensor. When choosing the resistor, make sure you don't overpower the `pull-down` resistor in the sensor (read the documentation to find out how big is the `pull-down`).
